export enum Currency {
    USD = 'USD', // US Dollar
    EUR = 'EUR', // Euro
    JPY = 'JPY', // Japanese Yen
    GBP = 'GBP', // British Pound
    AUD = 'AUD', // Australian Dollar
    CAD = 'CAD', // Canadian Dollar
    CHF = 'CHF', // Swiss Franc
    CNY = 'CNY', // Chinese Yuan Renminbi
    HKD = 'HKD', // Hong Kong Dollar
    NZD = 'NZD', // New Zealand Dollar
    SEK = 'SEK', // Swedish Krona
    KRW = 'KRW', // South Korean Won
    SGD = 'SGD', // Singapore Dollar
    NOK = 'NOK', // Norwegian Krone
    INR = 'INR', // Indian Rupee
    RUB = 'RUB', // Russian Ruble
    ZAR = 'ZAR', // South African Rand
    BRL = 'BRL', // Brazilian Real
    MXN = 'MXN', // Mexican Peso
    IDR = 'IDR', // Indonesian Rupiah
    TRY = 'TRY', // Turkish Lira
    SAR = 'SAR', // Saudi Riyal
    NGN = 'NGN', // Nigerian Naira
    PLN = 'PLN', // Polish Zloty
    ARS = 'ARS', // Argentine Peso
    VND = 'VND', // Vietnamese Dong
    THB = 'THB', // Thai Baht
    MYR = 'MYR', // Malaysian Ringgit
    PKR = 'PKR', // Pakistani Rupee
    ILS = 'ILS', // Israeli New Shekel
    DKK = 'DKK', // Danish Krone
    EGP = 'EGP', // Egyptian Pound
    COP = 'COP', // Colombian Peso
    CLP = 'CLP', // Chilean Peso
    CZK = 'CZK', // Czech Koruna
    HUF = 'HUF', // Hungarian Forint
    AED = 'AED', // United Arab Emirates Dirham
    QAR = 'QAR', // Qatari Riyal
    KWD = 'KWD', // Kuwaiti Dinar
    BDT = 'BDT', // Bangladeshi Taka
    PHP = 'PHP', // Philippine Peso
    LKR = 'LKR', // Sri Lankan Rupee
    UAH = 'UAH', // Ukrainian Hryvnia
    KES = 'KES', // Kenyan Shilling
    GHS = 'GHS', // Ghanaian Cedi
}
